export const ICON_NAMES = {
  profile: "profile",
  basket: "basket",
  arrowRight: "arrowRight",
  arrowLeft: "arrowLeft",
  cross: "cross",
  loader: "loader",
  customer: "customer",
  delivery: "delivery",
  address: "address",
  payment: "payment",
  mobileMenu: "mobileMenu",
  catalog: "catalog",
  changePassword: "changePassword",
  myInfo: "myInfo",
  orderHistory: "orderHistory",
  chat: "chat",
}   
