export const PAGES = {
  main: "/",
  catalog: "/catalog",
  category: "/catalog/:slug",
  product: "/catalog/product/:slug",
  delivery: "/delivery",
  exchange: "/exchange",
  contacts: "/contacts",
  oferta: "/oferta",
  politics: "/politics",
  order: "/order",
  user: "/user",
  paymentSuccess: "/payment-success",
  paymentError: "/payment-error",
  return: "/user",
  verify: "/verify-registration/:user/:hash",
  resetPassword: "reset-password",
}
