export const PAGES = {
  main: "/",
  catalog: "/catalog",
  category: "/catalog/:slug",
  product: "/catalog/product/:slug",
  delivery: "/delivery",
  exchange: "/exchange",
  contacts: "/contacts",
  oferta: "/oferta",
  politics: "/politics",
  order: "/order",
  user: "/user",
  return: "/user",
  verify: "/verify-registration/:id/:hash",
}
